### ISSUE TITLE
Repaints on scroll in the panel

### ISSUE THREAD

**Issue by rasteiner** [getkirby/kirby#1095]
For chrome, there currently seems to be an issue with "repaints on scroll" in the panel. This seems to become especially noticeable if you have a single 1 column images section with 1 image in cards layout, which has a "ratio" set. 

On my PC with a gtx1080 the framerate drops visibly under 30fps when scrolling.
It seems to be caused by the `overflow-y:scroll` for `.k-panel-view`.

Giving that element its own layer (for example by setting a `transform: translateZ(0)`) seems to solve the issue.

see video on slack:
https://getkirby.slack.com/archives/CBN859614/p1539709871000100

**Comment by bastianallgeier** [comment]
Thanks for investigating! I just fixed it 👍

**Comment by fabianmichael** [comment]
@bastianallgeier @rasteiner I’ve stumbled across an issue related to the added `transform: translateZ(0)` on `.k-panel-view`, which was probably a good solution/hack back then. But unfortunately this causes problems with CodeMirror 6 and could possibly affect other libraries as well. For example, focusing the editor will sometimes cause the viewport to scroll randomly and the tooltip of CM’s autocomplete feature does not work with this setup.

IMHO, it would be worth opening this issue again and testing, whether the issue still exists in current versions of Chrome. If not, the fix should be removed. Should be an easy win by just testing scroll performance in the latest version of Chrome using the profiler.

See: https://github.com/getkirby/kirby/blob/38afb2d650f3764d23d732b23ae8f04ab9ffba69/panel/src/App.vue#L291

**Comment by fabianmichael** [comment]
Follow-up: I found the root cause of the problem with CodeMirror in a transformed element. When using `position: fixed` inside a transformed element, the fixed position becomes relative to the transformed element instead of the viewport. So basically the transform applied to `.k-panel-view` break fixed positioning for anything inside it without special treatment.

See https://www.achrafkassioui.com/blog/position-fixed-and-CSS-transforms/

**Comment by rasteiner** [comment]
According to my tests, removing all hints for Chrome to separate the `.panel-viewport` into its own layer still causes repaints on scroll (notice that for testing, `transform: translate3d(0, 0, 0);` needs to be removed from the CSS file - deleting it from the inspector doesn't cause Chrome to merge its layers). 
However, the painting itself seems to have become faster (I don't know if it's a faster Nvidia driver or maybe Chrome or maybe Windows), so the issue doesn't seem to be visible anymore (to the naked eye, at least on my pc).

Anyway `transform: translateZ(0)` isn't the only kind of hint we can give Chrome. 

https://youtu.be/JUGRkU6yd_4 (green flashes: repaints; cyan lines: layer tiles)

It should be tested if it's literally the `transform` that causes issues with CodeMirror or if it's the fact that the element has it's own layer.

**Comment by fabianmichael** [comment]
@rasteiner The transform does not affect rendering of the editor, it’s just the fact that fixed elements behave differently inside of a transformed element. There was another bug with absolute positioned scroll areas, which I reported and which has been solved in the latest release. But because of the transform, it still does not work inside of Kirby’s panel. Does `will-change` have the same side-effects?

An alternative solution for the panel could be, to use fixed positioning for the top bar and adding a `padding-top` to either the body or `.k-panel-view`. This would also solve a bunch of other problems, see: https://kirby.nolt.io/265

**Comment by rasteiner** [comment]
> Does will-change have the same side-effects?

I don't know, that's what I've meant: it should be tested if it's the "transform" or the layering that affects fixed elements. If it's the layers, having `will-change` (or really anything that causes them) would have the same problem.

**Comment by rasteiner** [comment]
> Does will-change have the same side-effects?

doesn't look like it should:
https://codepen.io/rasteiner/pen/vYgMrYN

**Comment by fabianmichael** [comment]
> > Does will-change have the same side-effects?
> 
> doesn't look like it should:
> https://codepen.io/rasteiner/pen/vYgMrYN

Cool, just tested and can confirm that. Maybe that’s an intermediate solution, then?
