### ISSUE TITLE
k-number-field Component should not require type=number

### ISSUE THREAD

**Issue by elyukai** [getkirby/kirby#2643]
**Describe the bug**  
The `<k-number-field>` component does not show an input field unless `type="number"` is specified. This error happens in my custom plugin.

**To Reproduce**  
Copy the sample code from https://getkirby.com/docs/reference/plugins/ui/number-field and use it in a custom Vue component. 

**Expected behavior**  
The `<k-number-field>` component should default to `type="number"` as that is what the component suggests it represents.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/11094577/84830375-99e08f80-b029-11ea-8c4e-2cf66fbbe439.png)
*Left:* `type="number"` explicitly used; *Right:* `type="number"` omitted

**Kirby Version**  
3.3.6

**Console output**  
There are no (JS) console outputs.

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78

**Smartphone (please complete the following information):**  
n/a

**Additional context**  
n/a

**Comment by lukasbestle** [comment]
Potentially fixed by the component refactoring in the upcoming 3.4 release.

**Comment by elyukai** [comment]
I don't know if that helps but I just switched to the `develop` branch to test it – and it still doesn't work for me.

Also, when it doesn't work, it shows the following HTML structure:

![grafik](https://user-images.githubusercontent.com/11094577/84902645-5d567780-b0ad-11ea-8627-ed94901b38a8.png)

It also seems it's not only the `k-number-field` component but the `k-tags-field` as well that doesn't seem to work properly – difference is, I can't fix the `k-tags-field` component. At least I don't know how to. Shall I create a new issue for that one? Seems to be related, though:

![grafik](https://user-images.githubusercontent.com/11094577/84903009-d524a200-b0ad-11ea-9684-5862407a11fb.png)

**Comment by lukasbestle** [comment]
@elyukai The refactoring is not yet merged to the `develop` branch, try the `storybook` branch (however you do need to build the Panel assets yourself with `cd panel; npm install; npm run build`). :)

**Comment by elyukai** [comment]
Sadly, it still didn't work. 😕

![grafik](https://user-images.githubusercontent.com/11094577/84939599-dde19c00-b0de-11ea-9fba-ad8f0ac20fa5.png)

**Comment by distantnative** [comment]
I think this might still exists even in the refactored UI components. I will try to have a look.

And no need for a second issue. The root is the same problem.

**Comment by bastianallgeier** [comment]
✅
