### ISSUE TITLE
IM thumb engine fails at processing large image files

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#3023]
Kirby 3.4.3 (maybe 3.4.x) reintroduced the issue #1788 and reported by @silllli

**Comment by silllli** [comment]
I just encountered it again (Kirby 3.6.0). It’s just so frustrating. Felix posted a [possible solution in the forum](https://forum.getkirby.com/t/handling-broken-thumbs/13337/15).

Edit: the solution prevents the failing thumbnail creation, not fixing the missing check.

**Comment by silllli** [comment]
Before I was able to delete the broken thumbnails and Kirby—now “focussing” on these single images—was able to create them in the correct size. On my current project this is not the case and the thumbnail creation keeps failing. What is the official recommendation for this situation?

Maybe there needs to be some sort of system check during installation that recommends maximum image dimensions. I usually tell my clients to upload the best quality possible to be future-safe—but this doesn’t seem to be working anymore, with image files getting larger and larger.

**Comment by silllli** [comment]
Shall I start working on a PR? This is a huge problem that I have in almost every project. I wouldn’t want to use a different CMS.

**Comment by bastianallgeier** [comment]
@silllli if you find a solution, this would be fantastic! We are currently still focussing on 3.6.2 and the date field issues.

**Comment by silllli** [comment]
I think there are two tasks here:
1. Optimize memory usage during thumbnail creation, which will probably make the problem occur less often. The suggested solution from the forum that I linked to before guides in a direction.
2. Stop simply falling back to the source file if thumbnail creation fails on the first attempt. It needs to be decided what happens instead—how many retries make sense and in case it is concluded that a certain image can’t be resized in the current environment, how will the site owner be informed about it? I think I agree with this comment https://github.com/getkirby/kirby/commit/0db632aa76484cb263cab8a9ed545a304d24048a#r33938782, since it will be more obvious that something is wrong.

**Comment by silllli** [comment]
I’ve added the size hint which in fact saves a lot of memory and speeds up downscaling. Nevertheless it doesn’t prevent the failing of downscaling of large images to large thumbnail sizes (in this case the size hint doesn’t do anything). I still need to dig deeper into this but right now it seems pretty complicated to debug ImageMagick—the process simply stops without an error.

**Comment by silllli** [comment]
I think I found the solution: ImageMagick gets killed by the server because it uses too much memory. When I tried to use its `-limit` option to limit memory usage, it didn’t seem to have any effect. One of these problems you could go crazy with… I later found out that I used the options in the wrong order—the memory limit needs to be set _before_ the image is loaded in the command chain. Makes sense somehow.
The only downside is that thumbnail creation becomes very slow, because data that doesn’t fit into the allocated memory needs to be written to disk. This is in my opinion still a way better option than failing and only applies to “large input to large output” resizing in environments with restricted resources. Also it only happens when loading the image for the first time.

In order to prevent ImageMagick from being killed, we need to find out the available memory and set IMs memory limit respectively. I will update my PR in this regard.

It still needs to be decided if Kirby should respond with an error rather than the source file (which may not be cropped, converted to grayscale etc.) when the creation fails anyways. Moreover these fixes only help when not using the default driver.

**Comment by mrflix** [comment]
Thanks for the research, Silvan. If its not possible to detect the available memory I think a config option like `thumbs.memory = 512` would work well.

**Comment by silllli** [comment]
@afbora I think this issue can be renamed since the actual problem is not a missing check.

After some further research, this is what I understand: it indeed seems to be a very difficult (i.e. impossible) task to find out how much memory is available to ImageMagick beforehand. The system can change the value during runtime anyways. That’s why IM actually _should_ be able to handle this case well—but apparently the fallbacks don’t work on some (shared) servers.
My proposition would be what @mrflix also suggested, to simply add a config option which developers can use to set IM’s memory limit by approximation until a working value is found.

I am waiting for my PR to be rebased so I can add all this.

**Comment by silllli** [comment]
By the way: 

> I later found out that I used the options in the wrong order—the memory limit needs to be set before the image is loaded in the command chain

I think the `-limit thread 1` option which can be found in Kirby’s ImageMagick driver should also be set before the image is loaded.

**Although**: I wonder if it is necessary at all. The driver’s function comment says it’s supposed to limit the amount of files which are processed at the same time—this would actually be done with `-limit file 1`, not `thread`—but since the convert command is called with one file a time it’s not needed anyways.

**Comment by lukasbestle** [comment]
@silllli

Regarding `-limit thread 1`: AFAIK we added that for shared hosting plans where excessive CPU usage peaks are not welcome. The code comment about "too many files in parallel" was wrong. I have already fixed that together with the argument order in #4109.

Regarding the memory limit: We generally don't really like more and more configuration options as it makes the setup more complex and harder to grasp. But I agree that it makes sense here. The question is just what the default value should be.

**Comment by mrflix** [comment]
I would set the initial `thumbs.memoryLimit` value to `null`. I think it should be set explicitly by the website author when needed.

**Comment by silllli** [comment]
> I would set the initial `thumbs.memoryLimit` value to `null`. I think it should be set explicitly by the website author when needed.

I agree—since it’s only needed when there is a problem anyways. The default (null / no `-limit memory`) would match the behavior up until now and leaves the default memory limit setting to ImageMagick.

**Comment by lukasbestle** [comment]
I agree! Before we invest time: What do you think about introducing an option for the IM memory limit, @getkirby/kirby-staff?

**Comment by silllli** [comment]
Just as a heads up: I added the memory limit option locally already. It made the situation better and most thumbnails are generated now, but for one very large image it still fails. Probably because some other limit is hit when the cache is written to disk instead of memory (CPU, timeout). That may be the moment when you need to upgrade the hosting plan.

**Comment by distantnative** [comment]
Makes sense to me. I'd probably rather name it `thumbs.memory`, feels a bit more consistent (camel-casing seems to me  rather rare in Kirby). But that's just a detail.

**Comment by lukasbestle** [comment]
#4106 is merged (thanks again @silllli). I'm leaving this issue open because of the additional enhancements we are discussing here.

**Comment by distantnative** [comment]
Is this still a regression after https://github.com/getkirby/kirby/pull/4106, @afbora @lukasbestle? Or should this be covered to an enhancement issue just for further improvements?

**Comment by lukasbestle** [comment]
@distantnative You are right, it's quite confusing at the moment. Maybe we should extract the relevant comments into a new enhancement issue and close this one.

**Comment by distantnative** [comment]
That would be ideal 👍

**Comment by lukasbestle** [comment]
I have created two new issues #4248 and #4249.
